"""remove rating

Revision ID: 71d591051a87
Revises: f0dd63a694a0
Create Date: 2025-07-10 20:58:16.560399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '71d591051a87'
down_revision: Union[str, None] = 'f0dd63a694a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('magnet_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('card', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('rating', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('card', 'magnet_link')
    # ### end Alembic commands ###
